
services:
  postgres:
    image: postgres:15
    container_name: stock-etl-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rhythm123
      POSTGRES_DB: stock_market
      
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:rhythm123@postgres:5432/stock_market
      PYTHONPATH: /opt/airflow/src:/opt/airflow
      _AIRFLOW_DB_MIGRATE: 'true'          # tells entrypoint to run db migrate
      _AIRFLOW_WWW_USER_CREATE: 'true'     # creates admin user automatically
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
      DB_URL: postgresql+psycopg2://postgres:rhythm123@postgres:5432/stock_market
    command: version
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:rhythm123@postgres:5432/stock_market
      AIRFLOW__WEBSERVER__SECRET_KEY: rhythm_secret_key
      PYTHONPATH: /opt/airflow/src:/opt/airflow
      DB_URL: postgresql+psycopg2://postgres:rhythm123@postgres:5432/stock_market
      
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:rhythm123@postgres:5432/stock_market
      DB_URL: postgresql+psycopg2://postgres:rhythm123@postgres:5432/stock_market
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./logs:/opt/airflow/logs

volumes:
  postgres-db-volume:
